// JSSatchell 2026

// Creates markers to fade the audio in and out of selected layers
// Effect options are created to use the markers or set a custom duration from the layer start/end point

var comp = app.project.activeItem;
var layers = comp.selectedLayers;

app.beginUndoGroup("Fade Audio");    

var ffx = createTempFFX();

for(var i = 0; i < layers.length; i++) {
   if (layers[i].hasAudio){
      layers[i].applyPreset(ffx);
   } else {
      layers.splice(i,1);
      i--;
   }
}

if (ffx.exists){
   ffx.remove();
}

for(var i = 0; i < layers.length; i++) {
      var newIn = layers[i].inPoint;
      var newOut = layers[i].outPoint;
      if (newIn>newOut) { // Check for reversed layers
         var flip = newOut;
         newOut = newIn;
         newIn = flip;
      }
      var inMrk = newIn + .5;
      var outMrk = newOut - .5;
      var inNme = new MarkerValue("Audio In");
      var outNme = new MarkerValue("Audio Out");
      
      layers[i].marker.setValueAtTime(inMrk, inNme);
      layers[i].marker.setValueAtTime(outMrk, outNme);

      createTempFFX(layers[i]);
      layers[i].effect("Fade Layers").name = "Fade Audio";

      layers[i].effect("Fade Audio").property("Based On").expression = 'try { inMark = thisLayer.marker.key("Audio In"); } catch (err) { inMark = false; }\
try { outMark = thisLayer.marker.key("Audio Out"); } catch (err) { outMark = false; }\
\
if ( !inMark && !outMark ) { 2 } else { value }';

   layers[i].effect("Fade Audio")("In/Out").expression = 'ddBased = thisLayer.effect("Fade Audio")("Based On").value;\
\
try { inMark = thisLayer.marker.key("Audio In"); } catch (err) { inMark = false; }\
try { outMark = thisLayer.marker.key("Audio Out"); } catch (err) { outMark = false; }\
\
if (ddBased == 1) {\
if (inMark && outMark) {\
value\
} else if ( value != 4 ) {\
if ( !inMark ){\
   3\
} else if ( !outMark ) {\
   2\
}\
} else { value }\
} else { value }';

/*
      // This section will allow for a symmetrical fade based on a single marker placement, but it also defaults to a symmetrical fade when one marker is removed.
      layers[i].effect("Fade Audio").property("Symmetrical Fade?").expression = 'ddBased = thisLayer.effect("Fade Audio")("Based On").value;\
io = thisLayer.effect("Fade Audio")("In/Out").value;\
try { inMark = thisLayer.marker.key("Audio In"); } catch (err) { inMark = false; }\
try { outMark = thisLayer.marker.key("Audio Out"); } catch (err) { outMark = false; }\
\
if (ddBased == 1 && io == 1) {\
if ( !inMark || !outMark ) { 1 } else { value }\
} else { value }';
*/

      layers[i].effect("Fade Audio").property("Fade Out Duration").expression = 'syncFade = thisLayer.effect("Fade Audio")("Symmetrical Fade?").value;\
inVal=thisLayer.effect("Fade Audio")("Fade In Duration").value;\
\
if (syncFade==1) { inVal } else { value }';
      
      layers[i].property("Audio Levels").expression = 'ddBased = thisLayer.effect("Fade Audio")("Based On").value;\
ddInOut = thisLayer.effect("Fade Audio")("In/Out").value;\
inDurSet = thisLayer.effect("Fade Audio")("Fade In Duration").value;\
outDurSet = thisLayer.effect("Fade Audio")("Fade Out Duration").value;\
syncFade = thisLayer.effect("Fade Audio")("Symmetrical Fade?").value;\
layerDuration = outPoint - inPoint;\
minVol = -50;\
rev = 0;\
newIn = inPoint;\
newOut = outPoint;\
\
try {\
   inMark = thisLayer.marker.key("Audio In");\
} catch (err) {\
   inMark=false;\
}\
\
try {\
   outMark = thisLayer.marker.key("Audio Out");\
} catch (err) {\
   outMark=false;\
}\
\
if (inPoint>outPoint) { // Check for reversed layers\
   var flip = outPoint;\
   newOut = inPoint;\
   newIn = flip;\
   rev = 1;\
}\
\
inStart = newIn;\
outEnd = newOut;\
inDur = 0;\
outDur = 0;\
\
if (ddBased == 1) {\
   if (inMark) {\
      if (inMark.duration > 0) {\
         if (rev == 0) {\
            inStart = inMark.time;\
            inDur = (inMark.time + inMark.duration) - inStart;\
         } else {\
            inStart = inMark.time;\
            inDur = (inMark.time - inMark.duration) - inStart;\
         }\
      } else {\
         inDur = inMark.time - inStart;\
      }\
   }\
   if (outMark){\
      if (outMark.duration > 0) {\
		 if (rev == 0) {\
			outEnd = outMark.time + outMark.duration;\
		 } else {\
			outEnd = outMark.time - outMark.duration;\
		 }\
		 outDur = outEnd - outMark.time;\
      } else {\
         outDur = outEnd - outMark.time;\
      }\
   } else if ( syncFade == 1 ) {\
      outDur = inDur;\
   }\
   if ( !inMark && syncFade == 1) {\
      inDur = outDur;\
   }\
} else if (ddBased == 2) {\
   inDur = inDurSet;\
   outDur = outDurSet;\
}\
\
fadeIn = linear(time, inStart, inStart + inDur, minVol, value[0]);\
fadeOut = linear(time, outEnd - outDur, outEnd, value[0], minVol);\
\
if (ddInOut == 1) {\
   if (time < (layerDuration/2+inStart)) {\
      [fadeIn,fadeIn]\
   } else {\
      [fadeOut,fadeOut]\
   }\
} else if (ddInOut == 2) {\
   [fadeIn,fadeIn]\
} else if (ddInOut == 3) {\
   [fadeOut,fadeOut]\
} else if (ddInOut==4) {\
   value\
}';
}
app.endUndoGroup()


function createTempFFX() {
   var fadeLayers = "UklGWAAAEqxGYUZYaGVhZAAAABAAAAADAAAAYQAAAAUBAAAATElTVAAAEohiZXNjYmVzbwAAADgAAAABAAAAAQAAAAAAAF2oABf52wAAAAQAAQABB4AEOD/wAAAAAAAAP/AAAAAAAAAAAAAA/////0xJU1QAAACsdGRzcHRkb3QAAAAE/////3RkcGwAAAAEAAAAAkxJU1QAAABAdGRzaXRkaXgAAAAE/////3RkbW4AAAAoQURCRSBFZmZlY3QgUGFyYWRlAAAAAAAAAAAAAAAAAAAAAAAAAAAAAExJU1QAAABAdGRzaXRkaXgAAAAEAAAAAHRkbW4AAAAoUHNldWRvL1BFTSBGYWRlIENvbnRyb2xzIFYAAAAAAAAAAAAAAAAAAHRkc24AAAAUVXRmOAAAAAtGYWRlIExheWVycwBMSVNUAAAAZHRkc3B0ZG90AAAABP////90ZHBsAAAABAAAAAFMSVNUAAAAQHRkc2l0ZGl4AAAABP////90ZG1uAAAAKEFEQkUgRW5kIG9mIHBhdGggc2VudGluZWwAAAAAAAAAAAAAAAAAAABMSVNUAAARAHNzcGNmbmFtAAAAFlV0ZjgAAAAOVW5rbm93biBFZmZlY3RMSVNUAAAGCnBhclRwYXJuAAAABAAAAAd0ZG1uAAAAKFBzZXVkby9QRU0gRmFkZSBDb250cm9scyBWLTAwMDAAAAAAAAAAAABwYXJkAAAAlAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/////wAAAAAAAAAAAAAAAAAAAAB0ZG1uAAAAKFBzZXVkby9QRU0gRmFkZSBDb250cm9scyBWLTAwMDEAAAAAAAAAAABwYXJkAAAAlAAAAAAAAAAAAAAAAAAAAAdCYXNlZCBPbgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQACAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABwZG5tAAAAHFV0ZjgAAAAUTWFya2Vyc3xJbi9PdXQgUG9pbnR0ZG1uAAAAKFBzZXVkby9QRU0gRmFkZSBDb250cm9scyBWLTAwMDIAAAAAAAAAAABwYXJkAAAAlAAAAAAAAAAAAAAAAAAAAAdJbi9PdXQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAEAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABwZG5tAAAAKlV0ZjgAAAAhSW4gJiBPdXR8SW4gT25seXxPdXQgT25seXxObyBGYWRlAHRkbW4AAAAoUHNldWRvL1BFTSBGYWRlIENvbnRyb2xzIFYtMDAwMwAAAAAAAAAAAHBhcmQAAACUAAAAAAAAAAAAAAAAAAAABFN5bW1ldHJpY2FsIEZhZGU/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHBkbm0AAAAIVXRmOAAAAAB0ZG1uAAAAKFBzZXVkby9QRU0gRmFkZSBDb250cm9scyBWLTAwMDQAAAAAAAAAAABwYXJkAAAAlAAAAAAAAAAAAAAAAAAAAApGYWRlIEluIER1cmF0aW9uAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP+AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEQWAAAAAAAAQKAAAD8AAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAB0ZG1uAAAAKFBzZXVkby9QRU0gRmFkZSBDb250cm9scyBWLTAwMDUAAAAAAAAAAABwYXJkAAAAlAAAAAAAAAAAAAAAAAAAAApGYWRlIE91dCBEdXJhdGlvbgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP+AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEQWAAAAAAAAQKAAAD8AAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAB0ZG1uAAAAKEFEQkUgRWZmZWN0IEJ1aWx0IEluIFBhcmFtcwAAAAAAAAAAAAAAAABwYXJkAAAAlAAAAAAAAAAAAAAAAAAAAAkAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABMSVNUAAAKrHRkZ3B0ZHNiAAAABAAAAAF0ZHNuAAAAFFV0ZjgAAAALRmFkZSBMYXllcnMAdGRtbgAAAChQc2V1ZG8vUEVNIEZhZGUgQ29udHJvbHMgVi0wMDAwAAAAAAAAAAAATElTVAAAAOx0ZGJzdGRzYgAAAAQAAAADdGRzbgAAAAhVdGY4AAAAAHRkYjQAAAB825kAAQABAAAAAQAAAABdqD8aNuLrHEMtP/AAAAAAAAA/8AAAAAAAAD/wAAAAAAAAP/AAAAAAAAAAAAAEBAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGNkYXQAAAAoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHRkcGkAAAAEAAACnnRkcHMAAAAEAAAAAHRkbW4AAAAoUHNldWRvL1BFTSBGYWRlIENvbnRyb2xzIFYtMDAwMQAAAAAAAAAAAExJU1QAAADcdGRic3Rkc2IAAAAEAAAAAXRkc24AAAAQVXRmOAAAAAhCYXNlZCBPbnRkYjQAAAB825kAAQABAAAAAQAEAABdqD8aNuLrHEMtP/AAAAAAAAA/8AAAAAAAAD/wAAAAAAAAP/AAAAAAAAAAAAAEBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGNkYXQAAAAoP/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHRkbW4AAAAoUHNldWRvL1BFTSBGYWRlIENvbnRyb2xzIFYtMDAwMgAAAAAAAAAAAExJU1QAAADadGRic3Rkc2IAAAAEAAAAAXRkc24AAAAOVXRmOAAAAAZJbi9PdXR0ZGI0AAAAfNuZAAEAAQAAAAEABAAAXag/Gjbi6xxDLT/wAAAAAAAAP/AAAAAAAAA/8AAAAAAAAD/wAAAAAAAAAAAABAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABjZGF0AAAAKD/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB0ZG1uAAAAKFBzZXVkby9QRU0gRmFkZSBDb250cm9scyBWLTAwMDMAAAAAAAAAAABMSVNUAAAA5nRkYnN0ZHNiAAAABAAAAAF0ZHNuAAAAGlV0ZjgAAAARU3ltbWV0cmljYWwgRmFkZT8AdGRiNAAAAHzbmQABAAEAAAABAAQAAF2oPxo24uscQy0/8AAAAAAAAD/wAAAAAAAAP/AAAAAAAAA/8AAAAAAAAAAAAAQEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAY2RhdAAAACg/8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAdGRtbgAAAChQc2V1ZG8vUEVNIEZhZGUgQ29udHJvbHMgVi0wMDA0AAAAAAAAAAAATElTVAAAAQR0ZGJzdGRzYgAAAAQAAAABdGRzbgAAABhVdGY4AAAAEEZhZGUgSW4gRHVyYXRpb250ZGI0AAAAfNuZAAEAAQAA/////wAAXag/Gjbi6xxDLT/wAAAAAAAAP/AAAAAAAAA/8AAAAAAAAD/wAAAAAAAAAAAACAkAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABjZGF0AAAAKD/gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB0ZHVtAAAACAAAAAAAAAAAdGR1TQAAAAhAFAAAAAAAAHRkbW4AAAAoUHNldWRvL1BFTSBGYWRlIENvbnRyb2xzIFYtMDAwNQAAAAAAAAAAAExJU1QAAAEGdGRic3Rkc2IAAAAEAAAAAXRkc24AAAAaVXRmOAAAABFGYWRlIE91dCBEdXJhdGlvbgB0ZGI0AAAAfNuZAAEAAQAA/////wAAXag/Gjbi6xxDLT/wAAAAAAAAP/AAAAAAAAA/8AAAAAAAAD/wAAAAAAAAAAAACAkAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABjZGF0AAAAKD/gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB0ZHVtAAAACAAAAAAAAAAAdGR1TQAAAAhAFAAAAAAAAHRkbW4AAAAoQURCRSBFZmZlY3QgQnVpbHQgSW4gUGFyYW1zAAAAAAAAAAAAAAAAAExJU1QAAAM2dGRncHRkc2IAAAAEAAAAAXRkc24AAAAcVXRmOAAAABNDb21wb3NpdGluZyBPcHRpb25zAHRkbW4AAAAoQURCRSBFZmZlY3QgTWFzayBQYXJhZGUAAAAAAAAAAAAAAAAAAAAAAExJU1QAAABWdGRncHRkc2IAAAAEAAAAAXRkc24AAAAOVXRmOAAAAAYtXzBfLy10ZG1uAAAAKEFEQkUgR3JvdXAgRW5kAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB0ZG1uAAAAKEFEQkUgRWZmZWN0IE1hc2sgT3BhY2l0eQAAAAAAAAAAAAAAAAAAAABMSVNUAAAA+nRkYnN0ZHNiAAAABAAAAAF0ZHNuAAAADlV0ZjgAAAAGLV8wXy8tdGRiNAAAAHzbmQABAAEAAP////8AAF2oPxo24uscQy0/8AAAAAAAAD/wAAAAAAAAP/AAAAAAAAA/8AAAAAAAAAAAAAgJAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAY2RhdAAAAChAWQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAdGR1bQAAAAgAAAAAAAAAAHRkdU0AAAAIQFkAAAAAAAB0ZG1uAAAAKEFEQkUgRm9yY2UgQ1BVIEdQVQAAAAAAAAAAAAAAAAAAAAAAAAAAAABMSVNUAAAA2nRkYnN0ZHNiAAAABAAAAAF0ZHNuAAAADlV0ZjgAAAAGLV8wXy8tdGRiNAAAAHzbmQABAAEAAAACAAQAAF2oPxo24uscQy0/8AAAAAAAAD/wAAAAAAAAP/AAAAAAAAA/8AAAAAAAAAAAAAQEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAY2RhdAAAACg/8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAdGRtbgAAAChBREJFIEdyb3VwIEVuZAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAdGRtbgAAAChBREJFIEdyb3VwIEVuZAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAcGd1aQAAABAAAAAAAAAAAAAAAAAAAAAAPD94cGFja2V0IGJlZ2luPSLvu78iIGlkPSJXNU0wTXBDZWhpSHpyZVN6TlRjemtjOWQiPz4KPHg6eG1wbWV0YSB4bWxuczp4PSJhZG9iZTpuczptZXRhLyIgeDp4bXB0az0iQWRvYmUgWE1QIENvcmUgMTAuMC1jMDAwIDI1LkcuZWY3MmU0ZSwgMjAyNS8wNi8yNy0xODo1NDowNSAgICAgICAgIj4KICAgPHJkZjpSREYgeG1sbnM6cmRmPSJodHRwOi8vd3d3LnczLm9yZy8xOTk5LzAyLzIyLXJkZi1zeW50YXgtbnMjIj4KICAgICAgPHJkZjpEZXNjcmlwdGlvbiByZGY6YWJvdXQ9IiIKICAgICAgICAgICAgeG1sbnM6ZGM9Imh0dHA6Ly9wdXJsLm9yZy9kYy9lbGVtZW50cy8xLjEvIgogICAgICAgICAgICB4bWxuczp4bXA9Imh0dHA6Ly9ucy5hZG9iZS5jb20veGFwLzEuMC8iCiAgICAgICAgICAgIHhtbG5zOnhtcE1NPSJodHRwOi8vbnMuYWRvYmUuY29tL3hhcC8xLjAvbW0vIgogICAgICAgICAgICB4bWxuczpzdEV2dD0iaHR0cDovL25zLmFkb2JlLmNvbS94YXAvMS4wL3NUeXBlL1Jlc291cmNlRXZlbnQjIj4KICAgICAgICAgPGRjOmZvcm1hdD5hcHBsaWNhdGlvbi92bmQuYWRvYmUuYWZ0ZXJlZmZlY3RzLnByZXNldC1hbmltYXRpb248L2RjOmZvcm1hdD4KICAgICAgICAgPHhtcDpDcmVhdG9yVG9vbD5BZG9iZSBBZnRlciBFZmZlY3RzIDIwMjYgKFdpbmRvd3MpPC94bXA6Q3JlYXRvclRvb2w+CiAgICAgICAgIDx4bXA6Q3JlYXRlRGF0ZT4yMDI2LTA0LTIyVDE0OjUzOjA0LTA1OjAwPC94bXA6Q3JlYXRlRGF0ZT4KICAgICAgICAgPHhtcDpNZXRhZGF0YURhdGU+MjAyNi0wNC0yMlQxNDo1MzowNC0wNTowMDwveG1wOk1ldGFkYXRhRGF0ZT4KICAgICAgICAgPHhtcDpNb2RpZnlEYXRlPjIwMjYtMDQtMjJUMTQ6NTM6MDQtMDU6MDA8L3htcDpNb2RpZnlEYXRlPgogICAgICAgICA8eG1wTU06SW5zdGFuY2VJRD54bXAuaWlkOjgzOTY3ZmVjLTNhYzktNjY0NS04MDY1LTFkOTVkNjhmMjYxZjwveG1wTU06SW5zdGFuY2VJRD4KICAgICAgICAgPHhtcE1NOkRvY3VtZW50SUQ+eG1wLmRpZDo4Mzk2N2ZlYy0zYWM5LTY2NDUtODA2NS0xZDk1ZDY4ZjI2MWY8L3htcE1NOkRvY3VtZW50SUQ+CiAgICAgICAgIDx4bXBNTTpPcmlnaW5hbERvY3VtZW50SUQ+eG1wLmRpZDo4Mzk2N2ZlYy0zYWM5LTY2NDUtODA2NS0xZDk1ZDY4ZjI2MWY8L3htcE1NOk9yaWdpbmFsRG9jdW1lbnRJRD4KICAgICAgICAgPHhtcE1NOkhpc3Rvcnk+CiAgICAgICAgICAgIDxyZGY6U2VxPgogICAgICAgICAgICAgICA8cmRmOmxpIHJkZjpwYXJzZVR5cGU9IlJlc291cmNlIj4KICAgICAgICAgICAgICAgICAgPHN0RXZ0OmFjdGlvbj5jcmVhdGVkPC9zdEV2dDphY3Rpb24+CiAgICAgICAgICAgICAgICAgIDxzdEV2dDppbnN0YW5jZUlEPnhtcC5paWQ6ODM5NjdmZWMtM2FjOS02NjQ1LTgwNjUtMWQ5NWQ2OGYyNjFmPC9zdEV2dDppbnN0YW5jZUlEPgogICAgICAgICAgICAgICAgICA8c3RFdnQ6d2hlbj4yMDI2LTA0LTIyVDE0OjUzOjA0LTA1OjAwPC9zdEV2dDp3aGVuPgogICAgICAgICAgICAgICAgICA8c3RFdnQ6c29mdHdhcmVBZ2VudD5BZG9iZSBBZnRlciBFZmZlY3RzIDIwMjYgKFdpbmRvd3MpPC9zdEV2dDpzb2Z0d2FyZUFnZW50PgogICAgICAgICAgICAgICA8L3JkZjpsaT4KICAgICAgICAgICAgPC9yZGY6U2VxPgogICAgICAgICA8L3htcE1NOkhpc3Rvcnk+CiAgICAgIDwvcmRmOkRlc2NyaXB0aW9uPgogICA8L3JkZjpSREY+CjwveDp4bXBtZXRhPgogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICAgICAgICAgCjw/eHBhY2tldCBlbmQ9InciPz4=";

   var fadeLayersDecode = base64Decode(fadeLayers);

   var fadeLayersFFX = new File(Folder.myDocuments.fsName + "/Adobe/After Effects 20" + app.buildName.substr(0,2) + "/User Presets/Test.ffx");
   fadeLayersFFX.encoding = 'BINARY';
   fadeLayersFFX.open('w');
   fadeLayersFFX.write(fadeLayersDecode);
   fadeLayersFFX.close();

   return fadeLayersFFX;
}

function base64Decode(input) {
    var keyStr = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=";
    var output = "";
    var chr1, chr2, chr3;
    var enc1, enc2, enc3, enc4;
    var i = 0;

    input = input.replace(/[^A-Za-z0-9\+\/\=]/g, "");

    while (i < input.length) {
        enc1 = keyStr.indexOf(input.charAt(i++));
        enc2 = keyStr.indexOf(input.charAt(i++));
        enc3 = keyStr.indexOf(input.charAt(i++));
        enc4 = keyStr.indexOf(input.charAt(i++));

        chr1 = (enc1 << 2) | (enc2 >> 4);
        chr2 = ((enc2 & 15) << 4) | (enc3 >> 2);
        chr3 = ((enc3 & 3) << 6) | enc4;

        output += String.fromCharCode(chr1);

        if (enc3 != 64) {
            output += String.fromCharCode(chr2);
        }
        if (enc4 != 64) {
            output += String.fromCharCode(chr3);
        }
    }

    return output;
}
